### ISSUE TITLE
Introduce concept of custom views

### ISSUE THREAD

**Issue by vik378** [strictdoc-project/strictdoc#1509]
For complex requirements documents its pretty common to have multiple attributes that are maintain by different roles. Displaying them all at the same time and in the same view however may cause confusion and loss of focus. Therefore most of the RM tools implement in some way a concept o customized view.

Lets assume that by default - if no view is defined - we see all attributes rendered. But if the VIEWS section is defined it can act in a more advanced way

Here is a proposal / example of how that VIEWS section could look like

```
[VIEWS]
- VIEW_ID: DEFAULT
   TAGS:
      REQUIREMENT:
        VISIBLE_FIELDS:
         - UID
         - STATEMENT
         - RATIONALE
      ASSUMPTION:
         VISIBLE_FIELD:
         - UID
         - STATEMENT
 - VIEW_ID: COMPLIANCE_CHECK
    TAGS:
        REQUIREMENT:
          VISIBLE_FIELDS:
          - UID
          - STATEMENT
          - ANTICIPATED_COMPLIANCE
          - MEANS_OF_COMPLIANCE
          - MEANS_OF_VERIFICATION
    HIDDEN_TAGS:
      - ASSUMPTION
```

This would also enable us to render Specifications in HTML / pdf with only the data that we want to share with a supplier / customer / stakeholder - for example you may want to hide reasoning, assumptions, design decisions while exporting your requirements to a supplier.
