### ISSUE TITLE
StrictDoc does not recognize source files with arbitrary extensions

### ISSUE THREAD

**Issue by KlfJoat** [strictdoc-project/strictdoc#1621]
Per `strictdoc about`, I'm running `Version: 0.0.48`.

I have a section in one of my Requirements...

```text
RELATIONS:
- TYPE: File
  VALUE: filename.ext
```
I have no `source_root_path` set.

And I always get this error...

```text
error: Requirement FUNC-2 references a file that does not exist: filename.ext.
```

It does not matter what I put into `VALUE`, I am unable to get it to work without the error. I've tried relative to where I'm running StrictDoc, relative to the sdoc file, even absolute file path, and it always happens.

```text
error: Requirement FUNC-2 references a file that does not exist: bin/filename.ext.
```
```text
error: Requirement FUNC-2 references a file that does not exist: ./bin/filename.ext.  
```
```text
error: Requirement FUNC-2 references a file that does not exist: ../bin/filename.ext.
```
```text
error: Requirement FUNC-2 references a file that does not exist: /home/klfjoat/myproj/bin/filename.ext.
```

As I searched the StrictDoc repo for code that might relate to my problem I noticed that all of the test cases I checked still use the old `REFS` key, I'm not sure if that is related or not. I also didn't see a test that involved relative directories.

**Comment by stanislaw** [comment]
Hi! Thanks for reporting this. Just to make sure: did you follow the docs https://strictdoc.readthedocs.io/en/stable/strictdoc_01_user_guide.html#traceability-between-requirements-and-source-code to activate the reqs-to-files feature in the config?

```
[project]

features = [
  "REQUIREMENT_TO_SOURCE_TRACEABILITY"
]
```

**Comment by KlfJoat** [comment]
FYI, `error: Requirement FUNC-2 references a file that does not exist: bin/filename.ext.` does not show up if that feature is not enabled.

But for completeness, here is my `strictdoc.toml` file...

```toml
[project]
title = "myproj"

#source_root_path = "bin/"

include_doc_paths = [
  "docs/*.sdoc"
]

features = [
  # Stable features that are enabled by default.
  "TABLE_SCREEN",
  "TRACEABILITY_SCREEN",
  "DEEP_TRACEABILITY_SCREEN",

  # Experimental features
  # "REQIF",
  # "HTML2PDF",
  "DIFF",
  "PROJECT_STATISTICS_SCREEN",
  # "STANDALONE_DOCUMENT_SCREEN",
  "REQUIREMENT_TO_SOURCE_TRACEABILITY"
]
```
