### ISSUE TITLE
Missing validation on "Edit Grammar" form in the frontend

### ISSUE THREAD

**Issue by dahbar** [strictdoc-project/strictdoc#1659]
Using the following example document:

```
[DOCUMENT]
TITLE: TestDoc
OPTIONS:
  MARKUP: HTML

[GRAMMAR]
ELEMENTS:
- TAG: REQUIREMENT
  FIELDS:
  - TITLE: UID
    TYPE: String
    REQUIRED: False
  - TITLE: TITLE
    TYPE: String
    REQUIRED: False
  - TITLE: STATEMENT
    TYPE: String
    REQUIRED: False
  - TITLE: MISSINGVALIDATION
    TYPE: String
    REQUIRED: False
  RELATIONS:
  - TYPE: Parent

[REQUIREMENT]
UID: REQ-001
TITLE: Test Document
STATEMENT: >>>
Test Statement
<<<
MISSINGVALIDATION: >>>
Test validation
<<<
```

The validation for the field title "MISSINGVALIDATION" works, and one is not able to have the title with small letters or with spaces in it.
If I then run the server with  `strictdoc server .` for this document and click on `edit grammar`, I can change the CUSTOM FIELD to "missing validation" and click save.

### Expected Behavior
When clicking save, it gives out an error. As the new title for the field doesn't meet the validation requirements.

### Actual Behavior
The example document gets rewritten with:
```
[DOCUMENT]
TITLE: TestDoc
OPTIONS:
  MARKUP: HTML

[GRAMMAR]
ELEMENTS:
- TAG: REQUIREMENT
  FIELDS:
  - TITLE: UID
    TYPE: String
    REQUIRED: False
  - TITLE: TITLE
    TYPE: String
    REQUIRED: False
  - TITLE: STATEMENT
    TYPE: String
    REQUIRED: False
  - TITLE: missing validation
    TYPE: String
    REQUIRED: False
  RELATIONS:
  - TYPE: Parent

[REQUIREMENT]
UID: REQ-001
TITLE: Test Document
STATEMENT: >>>
Test Statement
<<<
missing validation: >>>
Test ALL CAPS
<<<
```
