### ISSUE TITLE
Establishing relation-based needs for nodes

### ISSUE THREAD

**Issue by i-interprete-on-the-fly** [strictdoc-project/strictdoc#1729]
Currently it is possible to define requirements as well as arbitrary node types and relations between those. Each of those node types may need several other elements, for example I could want to have a requirement having a relation to a software unit, an architecture element or a test case specification.
For this scenario it would be useful to be able to specify a set of relations that a specific node has to have established and be able to view missing relations for the node. Depending on the current view there could be different ways of implementing a missing link indication.

What do you think about that?

**Comment by stanislaw** [comment]
I am missing enough free time cycles to consider this properly, given other higher-priority tasks. Are you using StrictDoc actively enough to come up with a proposal here?

Some quick thoughts:

- I could think of setting up a nodes relation at the document level (a dedicated grammar field) or node-level (a dedicated node field).
- I could think of telling a node that it has to have a specific relation. More than that, has this relation be to a given document identified by document UID/MID or to a node of a given type?

**Comment by stanislaw** [comment]
Two related things are being prepared for implementation in 2025 Q2, and it looks like we could also address this issue:

- https://github.com/strictdoc-project/strictdoc/issues/1229
- https://github.com/strictdoc-project/strictdoc/issues/2168

---

Here is an example of a possible solution:

```
[GRAMMAR]
ELEMENTS:
- TAG: REQUIREMENT
  FIELDS:
  - TITLE: MID
    TYPE: String
    REQUIRED: True
  - TITLE: STATEMENT
    TYPE: String
    REQUIRED: True
  RELATIONS:
  - TYPE: Parent
  - TYPE: File
  CONSTRAINTS:
  - TYPE: NodeMustHaveChild
     RELATED_NODE: JUSTIFICATION
```

- Constraints types could be easily extensible, not just MustHaveChild, MustHaveParent.
- Constraints could go at the node level but I cannot think of a good example right now.
- I am undecided whether the violation of VERSION value between a node and a relation from another node pointing to it with a VERSION should be embedded into StrictDoc by default or that should be a node-level constraint `MustValidateVersion`.

Any feedback regarding the structure of the grammar is appreciated.
