### ISSUE TITLE
Custom grammar without STATEMENT field causes exception

### ISSUE THREAD

**Issue by haxtibal** [strictdoc-project/strictdoc#1823]
StrictDocs custom grammar feature makes it quite versatile. One can not only document requirements, but also design elements, threats from threat modelling, test cases, and so on.

I defined a `THREAT` tag, notably without a `STATEMENT` field as it wouldn't have meaning in that context.

```
[GRAMMAR]
ELEMENTS:
- TAG: THREAT
  FIELDS:
  - TITLE: UID
    TYPE: String
    REQUIRED: TRUE
  - TITLE: TITLE
    TYPE: String
    REQUIRED: TRUE
  - TITLE: DESCRIPTION
    TYPE: String
    REQUIRED: False
  - TITLE: SEVERITY
    TYPE: SingleChoice(Low, Medium, High)
    REQUIRED: TRUE
  - TITLE: SCORE
    TYPE: String
    REQUIRED: False
```

With such a grammar `strictdoc export` (version 0.0.55) raises an exception

```
...
  File "/home/tdmg/.local/pipx/venvs/strictdoc/lib/python3.11/site-packages/strictdoc/backend/sdoc/models/node.py", line 459, in enumerate_meta_fields
    statement_field_index = grammar_field_titles.index(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: 'STATEMENT' is not in list
```

because `SDocNode.enumerate_meta_fields` depends on the `STATEMENT` field to encode a convention that says "each field before STATEMENT is a single line field".

Would it be possible to find a different convention and remove that hard coded dependency on `STATEMENT`, to support use cases where `STATEMENT` doesn't make sense?

**Comment by stanislaw** [comment]
Hi @haxtibal. This is something that I was waiting someone to ask for, and I wanted to relax the STATEMENT-convention myself.

The main reason why this was done this way was that the Web UI has to know which field is a primary field and display it accordingly. I don't have a good general solution to this just yet, so for now I simply extended StrictDoc to auto-detect the primary field from one of `{STATEMENT, DESCRIPTION, CONTENT}`. Your example has `DESCRIPTION`, so let me know if this extended but still hard-coded solution is enough for your use case. I added your example as one of the integration test that now passes. Otherwise, let me know which other primary fields would you want to have?

You can try installing StrictDoc Pip from the latest main branch and let me know if it works better:

pip install -U --pre git+https://github.com/strictdoc-project/strictdoc.git@main

An extra note:

A more flexible solution I considered was to extend the grammar element declaration to support a `PRIMARY_FIELD` where you would simply declare which field StrictDoc should treat as the primary one, e.g., `PRIMARY_FIELD: DESCRIPTION`. I am not doing this just yet unless you have the whole variety of primary fields to support.

```
ELEMENTS:
- TAG: REQUIREMENT
  PRIMARY_FIELD: DESCRIPTION
  FIELDS:
  - TITLE: UID
    TYPE: String
```
