### ISSUE TITLE
Bug: UI requirement validation fails if optional SingleChoice field is not entered

### ISSUE THREAD

**Issue by haxtibal** [strictdoc-project/strictdoc#1876]
To reproduce, start `strictdoc server` for the following empty document and go to the web UI.

```
[DOCUMENT]
TITLE: Overview

[GRAMMAR]
ELEMENTS:
- TAG: REQUIREMENT
  FIELDS:
  - TITLE: UID
    TYPE: String
    REQUIRED: True
  - TITLE: TITLE
    TYPE: String
    REQUIRED: False
  - TITLE: STATEMENT
    TYPE: String
    REQUIRED: True
  - TITLE: MAYBE
    TYPE: SingleChoice(A, B, C, D)
    REQUIRED: False
```

Then try to add a new requirement
- enter text in fields UID, TITLE, STATEMENT
- leave field MAYBE blank

Expectation: UI validation passes. It's ok to leave MAYBE blank, because it has `REQUIRED: False` in the grammar.

Actual: UI validation fails with "Node's MAYBE must be a value one of A, B, C, D. ".
