### ISSUE TITLE
manage auto-uid: UID field REQUIRED True leads to an error

### ISSUE THREAD

**Issue by simhein** [strictdoc-project/strictdoc#1896]
There is an issue, when using the manage auto-uid command and having the UID filed in the grammar marked as REQUIRED= True.
This leads to following behavior if the UID not added for the command:
```
Semantic error: Wrong field order for requirement: [STATUS, TYPE, COMPONENT, TITLE, STATEMENT]
Hint: Problematic field: STATUS. Compare with the document grammar: [UID, STATUS, TYPE, COMPONENT, TITLE, STATEMENT, USER_STORY] for type: REQUIREMENT.
```
for a document grammar like this:
```
[GRAMMAR]
ELEMENTS:
- TAG: REQUIREMENT
  FIELDS:
  - TITLE: UID
    TYPE: String
    REQUIRED: True
  - TITLE: STATUS
    TYPE: String
    REQUIRED: True
  - TITLE: TYPE
    TYPE: String
    REQUIRED: True
  - TITLE: COMPONENT
    TYPE: String
    REQUIRED: True
  - TITLE: TITLE
    TYPE: String
    REQUIRED: True
  - TITLE: STATEMENT
    TYPE: String
    REQUIRED: True
  - TITLE: USER_STORY
    TYPE: String
    REQUIRED: False
  RELATIONS:
  - TYPE: Parent
```
