### ISSUE TITLE
[LINK: <uid>] does not allow to express all valid UIDs

### ISSUE THREAD

**Issue by haxtibal** [strictdoc-project/strictdoc#1897]
Currently there are two different sets of allowed characters for a UID, depending on the UID context:
```
[DOCUMENT]
TITLE: Document UIDs must not contain dots or whitespaces.
UID: FOO_BAR_1

[REQUIREMENT]
UID: FOO BAR 2.
TITLE: Requirement UIDs may contain dots or whitespaces.
STATEMENT: Test.
```

That's because DOCUMENT, SECTION, LINK, ANCHOR syntax use `REGEX_UID = r"([A-Za-z0-9]+[A-Za-z0-9_\-]*)"` in their grammar, while requirements define UID as SDocNodeField which most often is matched with regex `\S.*`. [StrictDoc User Guide - UID](https://strictdoc.readthedocs.io/en/stable/strictdoc_01_user_guide.html#uid) confirms the latter:

> StrictDoc does not impose any limitations on the format of a UID. Examples: ... SAVOIR.OBC.PM.80

As a consequence, one can define `FOO BAR 2.`, but will get an exception when trying to reference it with `[LINK: FOO BAR 2.]`.

IMO:
- any UID that can be defined should also be usable in LINKs
- allowed UID characters should be the same in any context, for consistency and comprehensibility
- allowing whitespaces and dots is useful when copying requirements from external documents/standards to sdoc

**Comment by stanislaw** [comment]
You are catching many things that I wanted to do myself for a long time, these are great reminders :+1: 

Your IMOs are also how I see it.

**Comment by stanislaw** [comment]
Do you think you could create a good regex to catch all the cases and reuse it everywhere in the grammar? A few unit tests in the `passthrough*` group would be nice to have.

**Comment by haxtibal** [comment]
> Do you think you could create a good regex to catch all the cases and reuse it everywhere in the grammar?

Yes, should be doable, just can't promise when I get to it.

**Comment by haxtibal** [comment]
My initial thought was to have a special line for UID, just as it's already done for MID, something like
```
SDocNode[noskipws]:
  '[' !'SECTION' !SDocCompositeNodeTagName requirement_type = RequirementType ']' '\n'
  ('MID: ' mid = SingleLineString '\n')?
  ('UID: ' uid = UidString '\n')?
  fields *= SDocNodeField
  (
    'RELATIONS:' '\n'
    (relations += Reference)
  )?
;
```

But this would have a similar surprising effect as MID has right know:

With the current release 0.0.57, you can define two `MID` fields for the same element. The first is actually parsed and used as MID, the 2nd one is parsed as ordinary field with field name "MID".

```
[DOCUMENT]
MID: ab8b923ad66a4fa880d7e4892e5a9783
TITLE: How to confuse MIDs.
OPTIONS:
  ENABLE_MID: True

[GRAMMAR]
ELEMENTS:
- TAG: REQUIREMENT
  FIELDS:
  - TITLE: UID
    TYPE: String
    REQUIRED: True
  - TITLE: MID
    TYPE: String
    REQUIRED: False
  - TITLE: STATEMENT
    TYPE: String
    REQUIRED: True

[REQUIREMENT]
MID: cfabae931ae645708bcb95e99ed as77a254a
UID: REQ-1
MID: This is actually not the MID, but an ordinary field.
STATEMENT: Two fields named MID, yet this document validates.
```

If we do the same for UID, TextX will call either `SDocNode.__init__(uid="REQ-1", ...)` or `SDocNode.__init__(fields=[(field_name = "UID", parts = ["REQ-1"],], ...)`, depending on the position of the UID line. The first call would get a regex validated string, the second gets a wildcard string as always for fields.

The least surprising solution is IMO to forbid "MID" and "UID" as SDocNodeField field_name by grammar. What's your opinion?
