### ISSUE TITLE
CUSTOM GRAMMAR links issues

### ISSUE THREAD

**Issue by elfman2** [strictdoc-project/strictdoc#1928]
version 0.0.58
Cannot link doc A / RULE to parent B / OBJECTIVE

if grammar for REQUIREMENT is not present:
=> KeyError: 'REQUIREMENT'
else:
=> KeyError: 'RULE'

Custom grammar for doc A:
```
- TAG: RULE
  FIELDS:
  - TITLE: UID
    TYPE: String
    REQUIRED: False
  - TITLE: TITLE
    TYPE: String
    REQUIRED: False
  - TITLE: STATEMENT
    TYPE: String
    REQUIRED: False
  RELATIONS:
  - TYPE: Parent
    ROLE: to trace objective
```

Custom grammar for doc B:
```
- TAG: OBJECTIVE
  FIELDS:
  - TITLE: UID
    TYPE: String
    REQUIRED: False
  - TITLE: TITLE
    TYPE: String
    REQUIRED: False
  - TITLE: STATEMENT
    TYPE: String
    REQUIRED: False
```
