### ISSUE TITLE
Bug: Excel import generate unexpected .sdoc

### ISSUE THREAD

**Issue by johanenglund** [strictdoc-project/strictdoc#2031]
## Describe the bug

[test.xls](https://github.com/user-attachments/files/17944259/test.xls)

Import of the attached .xls gives the unexpected grammar below. Fields are in different order than columns in .xls, fields are repeated and fields that does not exist in .xls appeared. Maybe there are some required formatting of the .xls that I'm missing?

```
[GRAMMAR]
ELEMENTS:
- TAG: REQUIREMENT
  FIELDS:
  - TITLE: UID
    TYPE: String
    REQUIRED: False
  - TITLE: LEVEL
    TYPE: String
    REQUIRED: False
  - TITLE: STATUS
    TYPE: String
    REQUIRED: False
  - TITLE: TAGS
    TYPE: String
    REQUIRED: False
  - TITLE: TITLE
    TYPE: String
    REQUIRED: False
  - TITLE: STATEMENT
    TYPE: String
    REQUIRED: False
  - TITLE: RATIONALE
    TYPE: String
    REQUIRED: False
  - TITLE: COMMENT
    TYPE: String
    REQUIRED: False
  - TITLE: SOURCE
    TYPE: String
    REQUIRED: False
  - TITLE: AREA
    TYPE: String
    REQUIRED: False
  - TITLE: STATUS
    TYPE: String
    REQUIRED: False
  - TITLE: REQTYPE
    TYPE: String
    REQUIRED: False
  - TITLE: VERIFICATION
    TYPE: String
    REQUIRED: False
  - TITLE: OWNER
    TYPE: String
    REQUIRED: False
  - TITLE: RATIONALE
    TYPE: String
    REQUIRED: False
```
## Expected behavior

A grammar consisting of the column headers, in the same order.

## Environment

- Ubuntu 24.04
- Strictdoc 0.3.0
