### ISSUE TITLE
Bug: Forward function relation hides forward class relation for same file

### ISSUE THREAD

**Issue by haxtibal** [strictdoc-project/strictdoc#2113]
## Describe the bug

If a forward relation to function `file.py:somefunc` and a forward relation to class `file.py:SomeClass` is defined, the rendered sdoc will only show a file link to the function. It will not show a link to the class.

Note how function and class have different names. It's sufficient to target the same file to trigger the bug.

## To Reproduce

_input.sdoc_
```
[DOCUMENT]
TITLE: Hello world doc

[GRAMMAR]
ELEMENTS:
- TAG: REQUIREMENT
  FIELDS:
  - TITLE: MID
    TYPE: String
    REQUIRED: False
  - TITLE: UID
    TYPE: String
    REQUIRED: False
  - TITLE: TITLE
    TYPE: String
    REQUIRED: False
  - TITLE: STATEMENT
    TYPE: String
    REQUIRED: False
  RELATIONS:
  - TYPE: File

[REQUIREMENT]
UID: REQ-001
TITLE: Requirement Title 1
STATEMENT: >>>
Requirement with forward relations.
<<<
RELATIONS:
- TYPE: File
  VALUE: file.py
  FUNCTION: foo
- TYPE: File
  VALUE: file.py
  CLASS: Bar
```

_file.py_
```py
class Bar: pass


def foo(): pass
```

## Expected behavior

The rendered document should have two file links, one for the class and one for the function.

## Environment

Version: 0.7.0

## Additional context

I've stumbled upon this during #2104 and will attempt to fix it along with #2104. Problem is how FileTraceabilityIndex.create_traceability_info looks up function, then class - but only if file had no function.

Still opened a separate issue, since the bug is in main and could also be fixed independently.
