### ISSUE TITLE
Docs: "User Guide / 6. SDoc syntax" needs to be updated

### ISSUE THREAD

**Issue by mettta** [strictdoc-project/strictdoc#2330]
**User Guide 
6. SDoc syntax** needs to be updated:

+ UID is not included in the list of reserved fields for DOCUMENT and NODE.

+ FUNCTION
```
  RELATIONS:
  - TYPE: File
    VALUE: file.c
    FUNCTION: Foo.hello_world_2
```
`FUNCTION` is described in paragraph `10.3. Linking requirements to source code`, but is missing in paragraph `6.2.4.10. RELATIONS`.
