### ISSUE TITLE
Bug: AttributeError: 'NoneType' object has no attribute 'required'

### ISSUE THREAD

**Issue by stanislaw** [strictdoc-project/strictdoc#675]
```
[DOCUMENT]
TITLE: Hello world doc

[SECTION]
TITLE: Section 1

[REQUIREMENT]
UID: A1
TITLE: Foo Title
STATEMENT: Requirement 7.8.9

[REQUIREMENT]
STATEMENT: Requirement 7.8.9

[REQUIREMENT]
UID: A1
TITLE: Foo Title
TAGS: #A, #B, #C
STATEMENT: Requirement 7.8.9
COMMENT: Foo

[/SECTION]
```

Triggers an exception:

```
    validate_requirement(requirement, document_grammar)
    assert not grammar_field.required
AttributeError: 'NoneType' object has no attribute 'required'
```

The problematic field is `TAGS:`.

**Comment by stanislaw** [comment]
Related issue:

```
[DOCUMENT]
TITLE: User Manual
OPTIONS:
  REQUIREMENT_STYLE: Inline
  REQUIREMENT_IN_TOC: True

[GRAMMAR]
ELEMENTS:
- TAG: REQUIREMENT
  FIELDS:
  - TITLE: UID
    TYPE: String
    REQUIRED: True
  - TITLE: TITLE
    TYPE: String
    REQUIRED: True
  - TITLE: STATEMENT
    TYPE: String
    REQUIRED: True
  - TITLE: COMMENT
    TYPE: String
    REQUIRED: True
  - TITLE: CONTENT
    TYPE: String
    REQUIRED: True
```

does not result in missing `CONTENT` field validation errors.
