### ISSUE TITLE
export/rst: doens't render the custom fields

### ISSUE THREAD

**Issue by BenGardiner** [strictdoc-project/strictdoc#779]
we are trying to use --formats=rst export in https://github.com/nmfta-repo/vcr-experiment to create a latexpdf.  We found that many of the fields in the grammar there 

```
[GRAMMAR]
ELEMENTS:
- TAG: REQUIREMENT
  FIELDS:
  - TITLE: UID
    TYPE: String
    REQUIRED: True
  - TITLE: LEVEL
    TYPE: String
    REQUIRED: False
  - TITLE: STATUS
    TYPE: String
    REQUIRED: False
  - TITLE: REFS
    TYPE: String
    REQUIRED: False
  - TITLE: TITLE
    TYPE: String
    REQUIRED: False
  - TITLE: STATEMENT
    TYPE: String
    REQUIRED: False
  - TITLE: TAGS
    TYPE: String
    REQUIRED: False
  - TITLE: RATIONALE
    TYPE: String
    REQUIRED: False
  - TITLE: COMMENT
    TYPE: String
    REQUIRED: False
  - TITLE: PUB_REFS
    TYPE: String
    REQUIRED: False
  - TITLE: VERIFICATION
    TYPE: String
    REQUIRED: False
  - TITLE: CRITICALITY
    TYPE: String
    REQUIRED: False
```

aren't rendered in the rst file. i.e. CRITICALITY, VERIFICATION, PUB_REFS

Is there a configuration we can set to render these extra/custom fields?
